<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sanjay" ignored="0" name="MiniCaseStudy" tests="4" failures="1" timestamp="2023-03-08T17:09:16 IST" time="26.191" errors="0">
  <testcase name="login" time="3.592" classname="demoblaze.caseStudy"/>
  <testcase name="selectMultipleItems" time="6.022" classname="demoblaze.caseStudy"/>
  <testcase name="DeleteItemInCart" time="2.192" classname="demoblaze.caseStudy">
    <failure type="java.lang.AssertionError" message="did not expect [1] but found [1]">
      <![CDATA[java.lang.AssertionError: did not expect [1] but found [1]
at demoblaze.caseStudy.DeleteItemInCart(caseStudy.java:124)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DeleteItemInCart -->
  <testcase name="PlaceOrder" time="6.57" classname="demoblaze.caseStudy"/>
</testsuite> <!-- MiniCaseStudy -->
